### ISSUE TITLE
endpoints.yml的tracker_store如何设置

### ISSUE THREAD

**Issue by changingBin** [pengyou200902/Doctor-Friende#79]
我用的是docker neo4j跑得数据库graph后端，请问endpoints.yml的tracker_store如何设置

**Comment by Alwin4Zhang** [comment]
pip install pymysql then edit endpoints.yml
```
tracker_store:
    type: SQL
    dialect: "mysql+pymysql"  # the dialect used to interact with the db
    url: "localhost"  # (optional) host of the sql db, e.g. "localhost"
    port: 3306
    db: "rasa"  # path to your db
    username: "your username"  # username used for authentication
    password: "your password"  # password used for authentication
```
